config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
root "cars#index"

  resources :cars, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :favourites, only: [:create, :index]
  end
  resources :favourites, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites


  validates :brand, :model, :fuel, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
  validates :owner_id, presence: true

end

# if we had has_many :reviews, dependent: destroy
# this means if we dleete a car, all favouries
# associated with it will be deleted from the db too

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car

end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars

  validates :nickname, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car

  # don't need to validate id's because db schema already specifies null=false
  # validates :car_id, presence: true, uniqueness: { scope: :car_id }
  validates :comment, presence: true, length: { minimum: 6, too_short: "must have at least 6 characters" }
  validates :rating, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  # def new
  #   @car = Car.find(params[:car_id])
  #   @favourite = Favourite.new
  # end

  def index
    @favourites = Favourite.all
  end

  def create
    @favourite = Favourite.new
    @car = Car.find(params[:car_id])
    @favourite.car = @car
    if @favourite.save
      redirect_to car_favourites_path(@favourite)
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    # redirect_to car_favourites_path(@favourite)
    redirect_to favourite_path(@favourite)
  end

  # private

  # def favourite_params
  #   params.require(:favourite).permit(:car_id)
  # end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # def new
  #   @review = Review.find(params[:car_id])
  #   @review = Review.new
  # end

  def create
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<div class="banner">
<h1>Find a car for all your travel needs!</h1>
</div>

<div class="card-container">
  <div class="cards">
  <% @cars.each do |car| %>

  <%= link_to car_path(car) do %>
    <div class="card-car"
      style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url('https://images.unsplash.com/photo-1622665556164-1a41221d82ce?q=80&w=1315&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')">


      <div class="card-car-infos">
      <div>
        <h2><%= car.brand %></h2>
        <h2><%= car.model %></h2>
        <p>Short description here!</p>
      </div>
        <h3><%= car.fuel %></h3>
      </div>
    </div>
    <% end %>
    <% end %>
    </div>
</div>

app/views/cars/show.html.erb
<h1><%= @car.brand %></h1>
<h2><%= @car.model %></h2>
<h3><%= @car.year %></h3>
<h3><%= @car.fuel %></h3>

 <%# this will make a line %>
<hr>

<div class="new-form">

<h1>Write a Review</h1>
<%= simple_form_for [@car, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating, collection: 1..5 %>
  <%= f.submit "Add review" %>
<% end %>

</div>

<h2>Reviews:</h2>
<% @car.reviews.each do |review| %>
<p><%= review.comment %></p>
<p>Rating: <%= review.rating %></p>
<p>-----------------</p>
<% end %>

<h2>Add this car to your favourites</h2>
<%= simple_form_for [@car, @favourite] do |f| %>
<%= f.submit "favourite!", class: "btn" %>
<% end %>

app/views/favourites/index.html.erb
<div class="card-container">

<div class="card-car" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url('https://images.unsplash.com/photo-1622665556164-1a41221d82ce?q=80&w=1315&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')">

<%= link_to favourite_path(@favourites),
    data: { turbo_method: :delete,
    turbo_confirm: "Are you sure?"}, class: "btn-delete" do %>
    <i class="fa-solid fa-trash"></i>
    <% end %>
    
<% @favourites.each do |favourite| %>

      <div class="card-car-infos">
      <div>
        <h1><%= favourite.car.brand%></h1>
        <h2><%= favourite.car.model%></h2>
        <h3><%= favourite.car.fuel %></h3>
      </div>
        <h3><%= favourite.car.year %></h3>
<% end %>


      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-garage">
    <%= link_to cars_path, class: "navbar-brand" do %>
    <div class="logo_title">
      <%= image_tag 'road_trip.jpg' %>
      <h2>My Travel Garage</h2>
      </div>
      <% end %>

      <div>
        <%= link_to "Home", root_path %>
        |
        <%= link_to "My Favourites", cars_path %>
      </div>
</div>